"""
Export the live model to a workbook.

    python -m pipeline.to_excel

This is the descendant of the spreadsheet this project replaced, with the manual
parts removed. Everything that used to be typed in by hand -- the schedule, the
odds, the power ratings, the injuries, the weather, the final scores -- is now
fetched and solved, and this file is a snapshot of the result.

One thing is deliberately NOT carried over: the old Control Panel was an input,
where editing a cell changed the model. Here it is a read-only record of the
settings that produced this file, because the model runs in the pipeline, not in
Excel. Editing a number here would look like it did something and would not.
The place to change the model is config/settings.json.
"""

from __future__ import annotations

import json
import os
import sys

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "site", "data")

INK, MUTED = "1F2430", "6F7887"
RULE = Side(style="thin", color="D6DAE3")
F_TITLE = Font(name="Arial", size=15, bold=True, color=INK)
F_SUB = Font(name="Arial", size=9, italic=True, color=MUTED)
F_HEAD = Font(name="Arial", size=9, bold=True, color="FFFFFF")
F_BODY = Font(name="Arial", size=10, color=INK)
F_NUM = Font(name="Arial", size=10, color=INK)
F_KPI = Font(name="Arial", size=16, bold=True, color=INK)
F_MUTED = Font(name="Arial", size=9, color=MUTED)
FILL_HEAD = PatternFill("solid", fgColor="2A3340")
FILL_BAND = PatternFill("solid", fgColor="F2F3F6")


def _read(name, default):
    p = os.path.join(DATA, name + ".json")
    if not os.path.exists(p):
        return default
    with open(p, encoding="utf-8") as fh:
        return json.load(fh)


def _title(ws, title, sub):
    ws["A1"] = title
    ws["A1"].font = F_TITLE
    ws["A2"] = sub
    ws["A2"].font = F_SUB
    ws.row_dimensions[1].height = 22
    ws.row_dimensions[2].height = 30
    ws["A2"].alignment = Alignment(wrap_text=True, vertical="top")


def _table(ws, top_row, headers, rows, widths, fmts=None, name=None):
    for j, h in enumerate(headers, start=1):
        c = ws.cell(row=top_row, column=j, value=h)
        c.font, c.fill = F_HEAD, FILL_HEAD
        c.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
        c.border = Border(bottom=RULE)
    for i, row in enumerate(rows):
        for j, v in enumerate(row, start=1):
            c = ws.cell(row=top_row + 1 + i, column=j, value=v)
            c.font = F_NUM if isinstance(v, (int, float)) else F_BODY
            c.border = Border(bottom=RULE)
            if fmts and j - 1 < len(fmts) and fmts[j - 1]:
                c.number_format = fmts[j - 1]
            if i % 2 == 1:
                c.fill = FILL_BAND
    for j, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(j)].width = w
    last = top_row + len(rows)
    if name and rows:
        ref = f"A{top_row}:{get_column_letter(len(headers))}{last}"
        t = Table(displayName=name, ref=ref)
        t.tableStyleInfo = TableStyleInfo(name="TableStyleLight1", showRowStripes=False)
        ws.add_table(t)
    ws.freeze_panes = ws.cell(row=top_row + 1, column=1)
    return last


def build(path: str) -> str:
    meta = _read("meta", {})
    summary = _read("summary", {})
    board = _read("board", [])
    ledger = _read("ledger", [])
    ratings = _read("ratings", [])
    games = _read("games", [])
    perf = _read("performance", {})
    forecasts = _read("forecasts", [])
    weather = _read("weather", {})
    injuries = _read("injuries", {})
    cfg = meta.get("settings", {})
    symb = cfg.get("currency_symbol", "$")
    money = f'"{symb}"#,##0.00;("{symb}"#,##0.00);"—"'
    pctf, pct2 = "0.0%", "0.00"

    wb = Workbook()
    demo = bool(meta.get("demo"))

    # ---------------------------------------------------------------- Read Me
    ws = wb.active
    ws.title = "Read Me"
    _title(ws, "NFL Edge — Model Export",
           ("SIMULATED DATA — generated by tools/make_demo.py to show the layout. The teams are "
            "real; every game, line and result is invented. Run `python -m pipeline.build` for the "
            "real thing." if demo else
            f"Snapshot of the live model, generated {meta.get('generated_at','—')}. "
            "Read-only: the model runs in the pipeline, not in this file."))
    rows = [
        ["Best Bets", "Every qualified play with its projection, edge and stake."],
        ["Full Board", "Every market priced this week, including the passes and the reason for each."],
        ["Tier Accuracy", "How BEST BET / GOOD / LEAN / PASS calls have actually performed."],
        ["Game Predictions", "Every game the model projected, graded against the result — bet or no bet — with the market's number beside it."],
        ["Power Ratings", "Solved from results by ridge regression, with offence and defence split out."],
        ["Schedule & Results", "The full season, live scores, and the market line on each game."],
        ["Injuries", "The league injury report the model applied this run."],
        ["Weather", "Kickoff forecasts and the points each one took off the projected total."],
        ["Bet Ledger", "Every logged bet, its grade, P/L and closing line value."],
        ["Settings", "The exact configuration that produced this file. Read-only — edit config/settings.json."],
    ]
    _table(ws, 4, ["Sheet", "What's on it"], rows, [22, 96])
    ws["A15"] = ("Where the numbers come from: schedule, scores, odds, injuries and news are ESPN's "
                 "public API; weather is Open-Meteo. Neither needs a key. Ratings are solved from "
                 "results every run, so nothing in this file was typed in by a person.")
    ws["A15"].font = F_MUTED
    ws["A15"].alignment = Alignment(wrap_text=True, vertical="top")
    ws.merge_cells("A15:B18")

    # ------------------------------------------------------------- Best Bets
    ws = wb.create_sheet("Best Bets")
    _title(ws, "Best Bets", "Every play that cleared the thresholds, best edge first. "
                            "Edges are compressed — see Settings for why.")
    plays = [b for b in board if b.get("tier") != "PASS"]
    rows = [[b.get("tier"), b.get("matchup"), b.get("market"), b.get("pick"), b.get("price"),
             b.get("model_prob"), b.get("breakeven"), b.get("edge"), b.get("edge_raw"),
             b.get("line_gap"), b.get("confidence"),
             (b.get("projection") or {}).get("proj_away_pts"),
             (b.get("projection") or {}).get("proj_home_pts"),
             b.get("game_date", "")[:10]] for b in plays]
    _table(ws, 4,
           ["Tier", "Game", "Market", "Pick", "Price", "Model", "Break-even", "Edge", "Raw edge",
            "Line gap", "Confidence", "Proj away", "Proj home", "Date"],
           rows, [11, 16, 8, 20, 8, 9, 11, 9, 10, 10, 11, 11, 11, 12],
           [None, None, None, None, "+0;-0", pctf, pctf, pctf, pctf, "+0.0;-0.0", pct2,
            "0.0", "0.0", None],
           name="tblBest")

    # ------------------------------------------------------------ Full Board
    ws = wb.create_sheet("Full Board")
    _title(ws, "Full Board", "Every market the model priced, including everything it threw away "
                             "and why. The passes are the point — a model you only see when it "
                             "likes something cannot be judged.")
    rows = [[b.get("tier"), b.get("matchup"), b.get("market"), b.get("pick"), b.get("price"),
             b.get("model_prob"), b.get("breakeven"), b.get("edge"), b.get("ev"),
             b.get("confidence"), b.get("filtered") or b.get("tier_note") or ""] for b in board]
    _table(ws, 4,
           ["Tier", "Game", "Market", "Pick", "Price", "Model", "Break-even", "Edge", "EV",
            "Confidence", "Why not"],
           rows, [11, 16, 8, 20, 8, 9, 11, 9, 9, 11, 60],
           [None, None, None, None, "+0;-0", pctf, pctf, pctf, pctf, pct2, None],
           name="tblBoard")

    # --------------------------------------------------------- Tier Accuracy
    ws = wb.create_sheet("Tier Accuracy")
    _title(ws, "Tier Accuracy",
           "Every call the model has made, graded at a flat one unit — including the passes. "
           "If PASS wins as often as GOOD, the labels are decoration. A normal bet log cannot "
           "show you this, because it never records the bets you did not make.")
    def acc_rows(block: dict):
        return [[k, v.get("n"), v.get("settled"), v.get("record"), v.get("win_pct"),
                 v.get("breakeven"), v.get("units"), v.get("roi"), v.get("avg_edge")]
                for k, v in (block or {}).items()]
    hdr = ["", "Calls", "Settled", "Record", "Win %", "Needed", "Units", "ROI", "Avg edge"]
    fmt = [None, "0", "0", None, pctf, pctf, "+0.00;-0.00", pctf, pctf]
    last = _table(ws, 4, hdr, acc_rows(perf.get("by_tier")), [20, 9, 9, 12, 9, 9, 9, 9, 10], fmt,
                  name="tblTier")
    r = last + 3
    ws.cell(row=r, column=1, value="By market").font = F_TITLE
    last = _table(ws, r + 1, hdr, acc_rows(perf.get("by_market")), [20, 9, 9, 12, 9, 9, 9, 9, 10], fmt)
    r = last + 3
    ws.cell(row=r, column=1, value="By confidence").font = F_TITLE
    last = _table(ws, r + 1, hdr, acc_rows(perf.get("by_confidence")), [20, 9, 9, 12, 9, 9, 9, 9, 10], fmt)
    r = last + 3
    ws.cell(row=r, column=1, value="Favourites vs underdogs").font = F_TITLE
    last = _table(ws, r + 1, hdr, acc_rows(perf.get("by_fav_dog")), [20, 9, 9, 12, 9, 9, 9, 9, 10], fmt)
    r = last + 3
    ws.cell(row=r, column=1, value="Calibration — when the model says X, does X happen?").font = F_TITLE
    _table(ws, r + 1, ["Model said", "Calls", "Predicted", "Actual", "Gap"],
           [[c.get("bucket"), c.get("n"), c.get("predicted"), c.get("actual"), c.get("gap")]
            for c in (perf.get("calibration") or [])],
           [20, 9, 11, 11, 9], [None, "0", pctf, pctf, "+0.0%;-0.0%"])

    # ------------------------------------------------------- Game Predictions
    ws = wb.create_sheet("Game Predictions")
    fc = perf.get("game_forecasts") or {}
    L = fc.get("latest_forecast") or {}
    _title(ws, "Game Predictions",
           "Every game the model priced, graded on what happened, whether or not a bet was placed. "
           "Absolute error means nothing on its own -- the column that matters is the market's, "
           "beside it. " + str(fc.get("verdict") or ""))
    heads = [("Games graded", fc.get("graded")),
             ("Margin error", L.get("margin_mae")),
             ("Market margin error", L.get("market_margin_mae")),
             ("Difference", L.get("margin_vs_market")),
             ("Straight up", (L.get("straight_up") or {}).get("pct")),
             ("Model side ATS", (L.get("against_the_spread") or {}).get("pct")),
             ("Beat the market", (L.get("beat_market_margin") or {}).get("pct"))]
    for j, (k, v) in enumerate(heads, start=1):
        ws.cell(row=4, column=j, value=k).font = F_MUTED
        c = ws.cell(row=5, column=j, value=v)
        c.font = F_KPI
        c.number_format = pctf if k in ("Straight up", "Model side ATS", "Beat the market") else "0.00"
    rows = []
    for r in forecasts:
        last = r.get("latest") or {}
        rows.append([(r.get("date") or "")[:10], r.get("week"), r.get("matchup"),
                     last.get("model_margin"), last.get("market_spread"),
                     last.get("model_total"), last.get("market_total"),
                     r.get("actual_margin"), r.get("actual_total"),
                     last.get("model_margin_ae"), last.get("market_margin_ae"),
                     ("Yes" if last.get("su_correct") else "No") if "su_correct" in last else "",
                     ("Yes" if last.get("ats_correct") else "No") if "ats_correct" in last else "",
                     r.get("final_score")])
    _table(ws, 7,
           ["Date", "Wk", "Game", "Model margin", "Market spread", "Model total", "Market total",
            "Actual margin", "Actual total", "Model error", "Market error", "Winner right?",
            "Side covered?", "Final"],
           rows, [12, 5, 16, 12, 12, 11, 11, 12, 11, 11, 11, 12, 12, 20],
           [None, "0", None, "+0.0;-0.0", "+0.0;-0.0", "0.0", "0.0",
            "+0;-0", "0", "0.00", "0.00", None, None, None],
           name="tblForecasts")

    # ---------------------------------------------------------- Power Ratings
    ws = wb.create_sheet("Power Ratings")
    _title(ws, "Power Ratings",
           "Points better than an average team on a neutral field. The difference between two "
           "ratings is a projected margin. Solved from results — nothing here was typed in.")
    _table(ws, 4,
           ["#", "Team", "Move", "Rating", "Offence", "Defence", "Record", "PF/g", "PA/g",
            "Margin", "Last 5", "ATS", "O/U", "Games"],
           [[r.get("rank"), r.get("team"), r.get("move"), r.get("rating"), r.get("off"),
             r.get("def"), r.get("record"), r.get("ppg"), r.get("papg"), r.get("margin"),
             r.get("last5"), r.get("ats"), r.get("ou"), r.get("games")] for r in ratings],
           [6, 10, 8, 10, 10, 10, 10, 9, 9, 9, 9, 10, 10, 8],
           [None, None, "+0;-0", "+0.00;-0.00", "+0.00;-0.00", "+0.00;-0.00", None,
            "0.0", "0.0", "+0.0;-0.0", None, None, None, "0"],
           name="tblRatings")

    # ----------------------------------------------------- Schedule & Results
    ws = wb.create_sheet("Schedule & Results")
    _title(ws, "Schedule & Results",
           "The full season as ESPN reports it, with the market line on each game and the score "
           "once it lands.")
    _table(ws, 4,
           ["Date", "Wk", "Type", "Away", "Home", "Venue", "Spread", "Total", "ML away", "ML home",
            "Away pts", "Home pts", "Status"],
           [[(g.get("date") or "")[:10], g.get("week"),
             {1: "Pre", 2: "Reg", 3: "Post"}.get(g.get("season_type"), ""),
             g.get("away"), g.get("home"), g.get("venue"),
             (g.get("odds") or {}).get("spread_home"), (g.get("odds") or {}).get("total"),
             (g.get("odds") or {}).get("ml_away"), (g.get("odds") or {}).get("ml_home"),
             g.get("away_score"), g.get("home_score"), g.get("status")] for g in games],
           [12, 5, 6, 8, 8, 30, 9, 8, 9, 9, 10, 10, 22],
           [None, "0", None, None, None, None, "+0.0;-0.0", "0.0", "+0;-0", "+0;-0", "0", "0", None],
           name="tblSchedule")

    # ------------------------------------------------------------- Injuries
    ws = wb.create_sheet("Injuries")
    _title(ws, "Injuries",
           "ESPN's league report as applied this run. Out and IR count fully, Doubtful most of "
           "the way, Questionable barely at all.")
    rows = []
    for tid, lst in (injuries or {}).items():
        for i in lst or []:
            rows.append([tid, i.get("name"), i.get("position"), i.get("status"),
                         i.get("detail") or i.get("type"), i.get("comment")])
    _table(ws, 4, ["Team id", "Player", "Pos", "Status", "Injury", "Note"], rows,
           [10, 26, 7, 18, 18, 70], name="tblInjuries")

    # -------------------------------------------------------------- Weather
    ws = wb.create_sheet("Weather")
    _title(ws, "Weather",
           "Kickoff forecasts and the points each took off the projected total. Only wind moves "
           "the model much; domes are ignored entirely.")
    rows = []
    for gid, w in (weather or {}).items():
        f = w.get("forecast") or {}
        rows.append([gid, w.get("venue"), w.get("roof"), f.get("temp_f"), f.get("wind_mph"),
                     f.get("gust_mph"), f.get("precip_prob"), f.get("condition"),
                     w.get("total_adj"), " · ".join(w.get("reasons") or [])])
    _table(ws, 4,
           ["Game id", "Venue", "Roof", "Temp °F", "Wind", "Gust", "Precip %", "Conditions",
            "Total adj", "Why"],
           rows, [12, 32, 12, 9, 8, 8, 9, 18, 10, 44],
           [None, None, None, "0", "0", "0", "0", None, "+0.0;-0.0", None],
           name="tblWeather")

    # ----------------------------------------------------------- Bet Ledger
    ws = wb.create_sheet("Bet Ledger")
    _title(ws, "Bet Ledger",
           "Written once when the model qualified the bet, then only ever graded — never "
           "re-priced. That rule is what keeps the recorded ROI meaningful.")
    kpis = [("Starting", summary.get("starting_bankroll")), ("Current", summary.get("current_bankroll")),
            ("Staked", summary.get("staked")), ("P/L", summary.get("pnl")),
            ("ROI", summary.get("roi")), ("Win rate", summary.get("win_rate")),
            ("Avg CLV", summary.get("avg_clv"))]
    for j, (k, v) in enumerate(kpis, start=1):
        ws.cell(row=4, column=j, value=k).font = F_MUTED
        c = ws.cell(row=5, column=j, value=v)
        c.font = F_KPI
        c.number_format = pctf if k in ("ROI", "Win rate", "Avg CLV") else money
    _table(ws, 7,
           ["Placed", "Game", "Pick", "Price", "Stake", "Edge", "Tier", "Result", "P/L",
            "Closing", "CLV", "Final score"],
           [[(b.get("game_date") or "")[:10], b.get("matchup"), b.get("pick"), b.get("price"),
             b.get("stake"), b.get("edge"), b.get("tier"), b.get("result"), b.get("pnl"),
             b.get("closing_price"), b.get("clv_prob"), b.get("final_score")] for b in ledger],
           [12, 16, 20, 8, 10, 9, 11, 10, 11, 10, 9, 22],
           [None, None, None, "+0;-0", money, pctf, None, None, money, "+0;-0", "+0.0%;-0.0%", None],
           name="tblLedger")

    # ------------------------------------------------------------- Settings
    ws = wb.create_sheet("Settings")
    _title(ws, "Settings (read-only)",
           "The exact configuration that produced this file. Change the model in "
           "config/settings.json and the next scheduled run picks it up — editing a cell here "
           "would look like it did something and would not.")
    flat = []

    def walk(prefix, obj):
        for k, v in obj.items():
            if k.startswith("_"):
                continue
            if isinstance(v, dict):
                walk(f"{prefix}{k}.", v)
            elif isinstance(v, list):
                flat.append([f"{prefix}{k}", ", ".join(map(str, v))])
            else:
                flat.append([f"{prefix}{k}", v])
    walk("", cfg)
    flat += [["", ""], ["home_field_advantage (solved)", meta.get("home_field_advantage")],
             ["league_avg_points (solved)", meta.get("league_avg_points")],
             ["preseason prior", meta.get("prior_note")],
             ["generated_at", meta.get("generated_at")]]
    _table(ws, 4, ["Setting", "Value"], flat, [46, 60])

    wb.save(path)
    return path


def main() -> int:
    out = os.path.join(ROOT, "NFL_Edge_Model.xlsx")
    build(out)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
